kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app1
  template:
    metadata:
      labels: 
        app: app1
    spec:
      containers:
      - name: nginx
        image: lakshman143/deployment:2.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1 
metadata:   
  name: nginx
spec: 
  type: LoadBalancer
  selector:  #labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80
    nodePort: 30007



